version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '07:00'
      timezone: 'Europe/Berlin'
    versioning-strategy: auto
    groups:
      all:
        patterns:
          - '*'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: monthly
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: monthly
