version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '07:00'
      timezone: 'Europe/Berlin'
    versioning-strategy: auto
    groups:
      dev-all:
        patterns:
        - "*"
        
