version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      # TODO change to weekly when done
      interval: daily
      time: '7:00'
      timezone: 'Europe/Berlin'
    versioning-strategy: auto
