FROM node:25-alpine3.22 AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
RUN corepack enable

FROM base AS build
COPY . /build
WORKDIR /build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run --filter=ui build

FROM nginx:stable-alpine3.21-slim AS ui
COPY --from=build /build/packages/ui/dist /prod/ui
WORKDIR /prod/ui

RUN rm -rf /etc/nginx/conf.d/*
COPY ./packages/ui/nginx.conf /etc/nginx/conf.d/nginx-course-finder.conf

EXPOSE 80
EXPOSE 443
EXPOSE 443/udp
CMD ["nginx", "-g", "daemon off;"]