import type { Course } from '@prisma/client'

export const data: Course[] = [
  {
    creditPoints: 8,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Stefan Bensch'],
    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'ABAPGL6.WP',
    pdf: null,
    published: true,
    semesterHours: 6,
    title: { de: 'ABAP-Grundlagen', en: 'Fundamentals of ABAP' },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Dr.-Ing. Matthias Niedermaier'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'AST4.WP',
    pdf: null,
    published: true,
    semesterHours: 4,
    title: {
      de: 'Advanced Security Testing',
      en: 'Advanced Security Testing',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Matthias Regner, M.Eng.'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'AEKDS4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Agile Entwicklung eines Klick-Dummy-Spiels',
      en: 'Agile development of a Click-Dummy Game',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Dipl.-Inf. (FH) Gregor Liebermann, M.Sc.'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'SCRUM4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Agile Softwareentwicklung (Scrum)',
      en: 'Agile Software Development (Scrum)',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Dipl.-Inf. (FH) Dipl.-Designer (FH) Erich Seifert, MA'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'PYTHON4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Agile Webanwendungen mit Python',
      en: 'Agile Web Applications with Python',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Stefan Bensch'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'BEINF4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Betriebliche Informationssysteme',
      en: 'Business Information Systems',
    },
    varyingCP: null,
  },
  {
    creditPoints: 2,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Björn Steven Häckel'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'CHRIMG2.WP',
    pdf: null,

    published: true,
    semesterHours: 2,
    title: {
      de: 'Chancen- & Risikomanagement in Digitalisierten',
      en: 'Chance and Risk Management in Digitized Value',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Jürgen Scholz'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'COM4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: { de: 'Compiler', en: 'Compiler' },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Jürgen Scholz'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'COMDR.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: { de: 'Compiler (DR)', en: 'Compiler (DR)' },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Philip McClenaghan'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'CGDEV4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: { en: 'Computer Games Development' },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Christoph Buck'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'CES4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Corporate Entrepreneurship',
      en: 'Corporate Entrepreneurship',
    },
    varyingCP: null,
  },
  {
    creditPoints: 4,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Matthias Kolonko, Ph.D. (ONPU)'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'DB3.WP',
    pdf: null,

    published: true,
    semesterHours: 3,
    title: { de: 'Datenbanken', en: 'Database Management Systems' },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Rolf Winter'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'DAKO4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Datenkommunikation',
      en: 'Fundamentals of Data Communications',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr.-Ing. Thomas Kirchmeier'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'DAKOFZ4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Datenkommunikation im Fahrzeug',
      en: 'Data communication in the vehicle',
    },
    varyingCP: null,
  },
  {
    creditPoints: 3,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Matthias Kolonko, Ph.D. (ONPU)'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'DBANW3.WP',
    pdf: null,

    published: true,
    semesterHours: 3,
    title: { de: 'DB-Anwendungen', en: 'Database Applications' },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Christoph Buck'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'DIGINN4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: { de: 'Digitale Innovationen', en: 'Digital Innovation' },
    varyingCP: null,
  },
  {
    creditPoints: 7,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Norbert Gerth'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'DIBUS.WP',
    pdf: null,

    published: true,
    semesterHours: 6,
    title: {
      de: 'Digital Business Leadership Skills',
      en: 'Digital Business Leadership Skills',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Jens Lauterbach'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'DTO4.WP',
    pdf: null,
    published: true,
    semesterHours: 4,
    title: { en: 'Digital Transformation in Organizations' },
    varyingCP: null,
  },
  {
    creditPoints: 7,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Norbert Gerth'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'ECOMM6.WP',
    pdf: null,

    published: true,
    semesterHours: 6,
    title: { de: 'E-Commerce', en: 'Electronic-Commerce' },
    varyingCP: null,
  },
  {
    creditPoints: 7,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Peter Schulik, M.Sc.'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'ITFORE6.WP',
    pdf: null,

    published: true,
    semesterHours: 6,
    title: {
      de: 'Einführung in die IT Forensik',
      en: 'Basics of IT Forensics',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Dr. Phil. Alessandra Zarcone'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'EMSV4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Einführung in die maschinelle Sprachverarbeitung',
      en: 'Introduction to Natural Language Processing',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Michael Strohmeier'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'EROB4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Einführung in die Robotik',
      en: 'Introduction to Robotics',
    },
    varyingCP: null,
  },
  {
    creditPoints: 7,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Hubert Högl'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'LINUX6.WP',
    pdf: null,

    published: true,
    semesterHours: 6,
    title: { de: 'Embedded Linux', en: 'Embedded Linux' },
    varyingCP: null,
  },
  {
    creditPoints: 2,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Jürgen Scholz'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'EDPS2.WP',
    pdf: null,

    published: true,
    semesterHours: 2,
    title: {
      de: 'Entwicklung und Durchführung eines',
      en: 'Development and implementation of a programming',
    },
    varyingCP: null,
  },
  {
    creditPoints: 6,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Norbert Gerth'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'EXGD4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: { de: 'Existenzgründung', en: 'Business Start-Up' },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Alexander von Bodisco'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'PROG.2',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Fahrzeug-Zu-Fahrzeug Kommunikation',
      en: 'Car-2-Car Communication',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Gundolf Kiefer'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'FSD4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Formula Student Driverless',
      en: 'Formula Student Driverless',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['M.A. Katharina Heimrath'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'FGMG4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: { de: 'Führungsmanagement', en: 'Leadership management' },
    varyingCP: null,
  },
  {
    creditPoints: 8,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Wolfgang Kowarschick'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'FSWD6.WP',
    pdf: null,

    published: true,
    semesterHours: 6,
    title: {
      de: 'Fullstack-Webentwicklung',
      en: 'Fullstack Web Development',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Matthias Kolonko, Ph.D. (ONPU)'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'DEVOPS4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: { de: 'Grundlagen DevOps', en: 'Fundamentals of DevOps' },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Volodymyr Brovkov'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'HARSO.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Hard- und Software für das Internet der Dinge',
      en: 'Hard- and software for the internet of things',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Alexander von Bodisco'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'HIP.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Hochschul Innovationsprojekt',
      en: 'University Innovation Project',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Peter Rösch'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'INDBV4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Industrielle Bildverarbeitung',
      en: 'Industrial Image Processing',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr.-Ing. Thomas Kirchmeier'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'INDIV4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Industrielle Informationsverarbeitung',
      en: 'Industrial Data Processing',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Jürgen Scholz'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'INUM4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Informatik und Umwelt',
      en: 'Information technology and the environment',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Dipl.-Ing. Harald Röser'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'SAPERP4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Integrierte Geschäftsprozesse mit SAP ERP',
      en: 'Integrated Business Processes with SAP ERP',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Michael Kipp'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'INTENG4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: { en: 'Interaction Engineering' },
    varyingCP: null,
  },
  {
    creditPoints: 7,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Peter Rösch'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'IACOGR6.WP',
    pdf: null,

    published: true,
    semesterHours: 6,
    title: {
      de: 'Interaktive Computergrafik',
      en: 'Interactive Computer Graphics',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Stephan Zimmermann'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'ITC4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: { de: 'IT-Consulting', en: 'IT-Consulting' },
    varyingCP: null,
  },
  {
    creditPoints: 7,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Lothar Braun'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'ITSICH6.WP',
    pdf: null,

    published: true,
    semesterHours: 6,
    title: { de: 'IT-Sicherheit', en: 'IT Security' },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Arne Mayer'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'ITSCT4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: { en: 'IT Sourcing and Cloud Transformation' },
    varyingCP: null,
  },
  {
    creditPoints: 2,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Johannes Ewald, M.Sc.'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'JAVSCR2.WP',
    pdf: null,

    published: true,
    semesterHours: 2,
    title: { de: 'JavaScript', en: 'JavaScript' },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Wolfgang Kowarschick'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'KLPRO.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Klassische Projekttechniken modernisiert',
      en: 'Classic Project Management Modernized',
    },
    varyingCP: null,
  },
  {
    creditPoints: 2,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Harry Schäfle'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'ITSN2.WP',
    pdf: null,

    published: true,
    semesterHours: 2,
    title: {
      de: 'Kompaktmodul IT-Sicherheit in Computernetzen',
      en: 'Compact module IT security in computer networks',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Michael Predeschly'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'KDBT4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Konzepte der Datenbanktechnologie',
      en: 'Concepts of Database Technology',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Stephan Zimmermann'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'LEANIT4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: { en: 'Lean IT & Enterprise Architecture' },
    varyingCP: null,
  },
  {
    creditPoints: 2,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Dieter Thalmayr'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'LINLPI2.WP',
    pdf: null,

    published: true,
    semesterHours: 2,
    title: { de: 'Linux LPIC', en: 'Linux LPIC' },
    varyingCP: null,
  },
  {
    creditPoints: 2,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Dieter Thalmayr'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'LPICAD2.WP',
    pdf: null,

    published: true,
    semesterHours: 2,
    title: { de: 'Linux LPIC Advanced', en: 'Linux LPIC Advanced' },
    varyingCP: null,
  },
  {
    creditPoints: 7,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Thomas Rist'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'KI6.WP',
    pdf: null,

    published: true,
    semesterHours: 6,
    title: { de: 'Methoden der KI', en: 'Artificial Intelligence' },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Oliver Seitz M.Sc.,'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'MCODK4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Moderne Containerisierung und Orchestrierung mit',
      en: 'Modern Containerization and Orchestration with',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr.-Ing. Alexandra Teynor'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'MKML4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Mustererkennung und maschinelles Lernen',
      en: 'Pattern recognition and machine learning',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Dr. Lothar Braun'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'NETP.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Network Penetration Testing',
      en: 'Network Penetration Testing',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Michael Kipp'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'NNDL4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Neuronale Netze und Deep Learning',
      en: 'Neural Networks and Deep Learning',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Michael Predeschly'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'NoSQL4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: { de: 'NoSQL', en: 'NoSQL' },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr.-Ing. Thomas Kirchmeier'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'OPPYTH4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Objektorientierte Programmierung mit Python',
      en: 'Object-oriented programming with Python',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Hubert Högl'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'OSSWE4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Open-Source Softwareentwicklung',
      en: 'Open Source Software Development',
    },
    varyingCP: null,
  },
  {
    creditPoints: 7,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dipl.-Ing. Georg Stark'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'PRRO.WP',
    pdf: null,

    published: true,
    semesterHours: 6,
    title: {
      de: 'Praktische Robotik mit Matlab',
      en: 'Practical Robotics with Matlab',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Wolfgang Kratsch'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'PRCINT4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: { de: 'Process Intelligence', en: 'Process Intelligence' },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Matthias Kolonko, Ph.D. (ONPU)'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'DBP4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Programmieren mit Datenbanken',
      en: 'Programming using Databases',
    },
    varyingCP: null,
  },
  {
    creditPoints: 8,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Peter Rösch'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'PROGPY6.WP',
    pdf: null,

    published: true,
    semesterHours: 6,
    title: {
      de: 'Programmieren mit Python',
      en: 'Programming with Python',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Anja Metzner'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'PWA4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Programmierung von Web-Anwendungen',
      en: 'Programming of Web Applications',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Nik Klever'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'PRJU4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: { de: 'Project Jupyter', en: 'Project Jupyter' },
    varyingCP: null,
  },
  {
    creditPoints: 10,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Alexander von Bodisco'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'FUT.WP',
    pdf: null,

    published: true,
    semesterHours: 8,
    title: {
      de: 'Projekt - Forschung und Transfer',
      en: 'Project - Research and Transfer',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Volodymyr Brovkov'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'RFID3.WP',
    pdf: null,

    published: true,
    semesterHours: 3,
    title: { de: 'RFID und NFC Technik', en: 'RFID and NFC technology' },
    varyingCP: null,
  },
  {
    creditPoints: 2,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Kai de Wals'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'SEENG.WP',
    pdf: null,

    published: true,
    semesterHours: 2,
    title: {
      de: 'Search Engine Advertising in der Praxis (SEA)',
      en: 'Search Engine Advertising (SEA)',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Alexander von Bodisco'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'SLP.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Service Learning Projekt',
      en: 'Service Learning Project',
    },
    varyingCP: null,
  },
  {
    creditPoints: 2,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Dr. Marc Zeller (Siemens AG, München)'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'SRASYS2.WP',
    pdf: null,

    published: true,
    semesterHours: 2,
    title: {
      de: 'Sichere und robuste autonome Systeme',
      en: 'Safe and robust autonomous systems',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Phillip Heidegger'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'TYPSCR4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Single-Page Webanwendungen mit TypeScript und',
      en: 'Single-page applications with TypeScript and Angular',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Phillip Heidegger'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'SECloud.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Softwareentwicklung mit Cloud-Technologie',
      en: 'Software Development with cloud technology',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Dipl.-Wirt.-Inf. (FH) Andrea Obermeyer, MBA'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'SWPJMG.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Software-Projektmanagement',
      en: 'Software Project Management',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Christoph Buck'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'START4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Startitup - Entrepreneurial Thinking and Business',
      en: 'Startitup - Entrepreneurial Thinking and Business',
    },
    varyingCP: null,
  },
  {
    creditPoints: 2,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Christoph Baur, B.Sc.'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'SUCHMA.WP',
    pdf: null,

    published: true,
    semesterHours: 2,
    title: {
      de: 'Suchmaschinenoptimierung (SEO)',
      en: 'Search Engine Optimization (SEO)',
    },
    varyingCP: null,
  },
  {
    creditPoints: 6,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Hubert Högl'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'SNP5.WP',
    pdf: null,

    published: true,
    semesterHours: 5,
    title: { de: 'Systemnahe Programmierung', en: 'Systems programming' },
    varyingCP: null,
  },
  {
    creditPoints: 2,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Stefan Kaindl'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'UGES2.WP',
    pdf: null,

    published: true,
    semesterHours: 2,
    title: {
      de: 'Unternehmertum Grundlagen - Erfindergeist trifft Schaffensfreude',
      en: 'Entrepreneurship Basics - Inventiveness meets joy of creation',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Philip McClenaghan'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'VISTH.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: { en: 'Visual Thinking for Business' },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Markus Degen'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'IFPP4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Von Imperativ bis Funktional: Programmiersprachen',
      en: 'From Imperative to Functional: Programming',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Michael Jaser, M. Sc.'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'NODEJS4.WP',
    pdf: null,

    published: true,
    semesterHours: 4,
    title: {
      de: 'Web-Entwicklung mit Node.js',
      en: 'Web development with Node.js',
    },
    varyingCP: null,
  },

  // Master only
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Thomas Rist'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'AWKI.WP',
    pdf: null,
    published: true,
    semesterHours: 4,
    title: {
      de: 'Anwendungen der Künstlichen Intelligenz',
      en: 'Applied Artificial Intelligence',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Dipl.-Inf. (FH) Dipl.-Designer (FH) Erich Seifert, MA'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'BPAP3.WP',
    pdf: null,
    published: true,
    semesterHours: 4,
    title: {
      de: 'Business Process Application Programming',
      en: 'Business Process Application Programming',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Matùš Mala'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'BPM3.WP',
    pdf: null,
    published: true,
    semesterHours: 3,
    title: {
      de: 'Business Process Modelling',
      en: 'Business Process Modelling',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr.-Ing. Honorary Doctor of ONPU Thorsten Schöler'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'DASC4.WP',
    pdf: null,
    published: true,
    semesterHours: 4,
    title: {
      de: 'Data Science',
      en: 'Data Science',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Wolfgang Kowarschick', 'Prof. Michael Stoll'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'DATVIZ2.WP',
    pdf: null,
    published: true,
    semesterHours: 2,
    title: {
      de: 'Datenvisualisierung',
      en: 'Data Visualization',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Christoph Buck'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'DSDT2.WP',
    pdf: null,
    published: true,
    semesterHours: 2,
    title: {
      de: 'Disrupting Sports by Digital Technologies',
      en: 'Disrupting Sports by Digital Technologies',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Gundolf Kiefer'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'EFRE.WP',
    pdf: null,
    published: true,
    semesterHours: 2,
    title: {
      de: 'Effiziente- Rechner und Systemarchitekturen (DR)',
      en: 'Advanced Computer and System Architectures (DR)',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Arne Mayer'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'ELHS4.WP',
    pdf: null,
    published: true,
    semesterHours: 4,
    title: {
      de: 'Elektronische Handelssysteme',
      en: 'Electronic Trading Systems',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr.-Ing. Dominik Merli'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'EMBSEC.WP',
    pdf: null,
    published: true,
    semesterHours: 4,
    title: {
      de: undefined,
      en: 'Embedded Security',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Alexander von Bodisco'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'F2FKOM4.WP',
    pdf: null,
    published: true,
    semesterHours: 4,
    title: {
      de: 'Fahrzeug-Zu-Fahrzeug Kommunikation',
      en: 'Business Process Application Programming',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Johannes Ewald, M.Sc.'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'JAVASCR.WP',
    pdf: null,
    published: true,
    semesterHours: 2,
    title: {
      de: 'JavaScript',
      en: 'JavaScript',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Peter Rösch'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'MEDIBI.WP',
    pdf: null,
    published: true,
    semesterHours: 4,
    title: {
      de: 'Medizinische Bildverarbeitung',
      en: 'Medical Image Processing',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Dipl.-Inf. (FH) Dipl.-Designer (FH) Erich Seifert, MA'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'OOSD.WP',
    pdf: null,
    published: true,
    semesterHours: 3,
    title: {
      de: 'Object Oriented Software Development for Business Processes',
      en: 'Object Oriented Software Development for Business Processes',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Alexander von Bodisco'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'SKUP.WP',
    pdf: null,
    published: true,
    semesterHours: 4,
    title: {
      de: undefined,
      en: 'Secure Concepts and Protocols',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Jana Görmer-Redding'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'SGP2.WP',
    pdf: null,
    published: true,
    semesterHours: 2,
    title: {
      de: 'Sichere Geschäftsprozesse',
      en: 'Secure Business Processes',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Christoph Buck'],
    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'SDMDT4.WP',
    pdf: null,
    published: true,
    semesterHours: 4,
    title: {
      de: 'Smart Decision Making - Datenvisualisierung mit Tableau',
      en: 'Smart Decision Making - Data Visualization with Tableau',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Björn Häckel'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'S3G2.WP',
    pdf: null,
    published: true,
    semesterHours: 2,
    title: {
      de: undefined,
      en: 'Smart Sustainability Simulation Game (S3G)',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr. Jürgen Scholz'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'VERINF.WP',
    pdf: null,
    published: true,
    semesterHours: 2,
    title: {
      de: 'Vermittlung Informationstechnischer Inhalte',
      en: 'Explaning of Information Technology Content',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Dipl. Designer (FH) Fabian Ziegler'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'WEBTEC4.WP', // TODO WEBTECH.WP
    pdf: null,
    published: true,
    semesterHours: 4,
    title: {
      de: 'Web-Technologien',
      en: 'Web-Technologies',
    },
    varyingCP: null,
  },
  {
    creditPoints: 5,
    editorUsername: null,
    exam: null,
    extraInfo: null,
    faculty: 'Informatik',
    infoUrl: null,
    lecturers: ['Prof. Dr.-Phil. Alessandra Zarcone'],

    maExam: null,
    maPdf: null,
    minFocus: null,
    moduleCode: 'WSH2.WP',
    pdf: null,
    published: true,
    semesterHours: 2,
    title: {
      de: undefined,
      en: 'Workshop: Introduction to scientific research',
    },
    varyingCP: null,
  },
]
