# keep in sync with dev

services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile.api
      target: api
    env_file:
      - ./.env
    restart: unless-stopped

  ui:
    build:
      context: ../
      dockerfile: Dockerfile.ui
      target: ui
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ${CERTS_PRIVKEY}:/prod/certs/privkey.pem
      - ${CERTS_CHAIN}:/prod/certs/chain.pem
      - ${CERTS_FULLCHAIN}:/prod/certs/fullchain.pem
      - ./subject-enroll.conf.local:/etc/nginx/conf.d/subject-enroll.conf
    depends_on:
      - api

    restart: unless-stopped
