# keep in sync with prod

networks:
  proxy-network:
    external:
      name: proxy-network

services:
  api:
    build:
      context: ../
      target: api
    env_file:
      - ./.env
    ports:
      - 2022:2022
    network_mode: bridge

    restart: unless-stopped
    depends_on:
      - database
  ui:
    build:
      context: ../
      target: ui
    ports:
      - 3000:3000
    restart: unless-stopped

  reverse-proxy:
    build: ./reverse-proxy
    cap_add:
      - NET_ADMIN
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    network:
      - proxy-network
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config

    restart: unless-stopped

  database:
    image: postgres:alpine
    env_file:
      - ./.env
    ports:
      - 5432:5432
    network_mode: bridge

    restart: unless-stopped
