# keep in sync with prod

services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile.api
      target: api
    env_file:
      - ./.env
    network_mode: bridge
    links:
      - database

    restart: unless-stopped
    depends_on:
      - database

  ui:
    build:
      context: ../
      dockerfile: Dockerfile.ui
      target: ui
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      # TODO use server
      - /etc/letsencrypt/live/example.com/:/prod/certs
      - ./docker/subject-enroll.conf:/etc/nginx/conf.d/subject-enroll.conf
    network_mode: bridge
    links:
      - api
    depends_on:
      - api

    restart: unless-stopped

  database:
    image: postgres:alpine
    env_file:
      - ./.env
    network_mode: bridge
    volumes:
      - ./docker/database:/var/lib/postgresql/data
    ports:
      # only development
      - '5432:5432'

    restart: unless-stopped
