# keep in sync with dev
services:
  api:
    build:
      context: ../
      target: api
    env_file:
      - ./.env
    ports:
      - 2022:2022
    network_mode: bridge
    restart: always
  ui:
    build:
      context: ../
      target: ui
    ports:
      - 3000:3000
    restart: always
