/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminCreateEnroll: typeof import('./src/components/admin/AdminCreateEnroll.vue')['default']
    AdminSubjectList: typeof import('./src/components/admin/AdminSubjectList.vue')['default']
    AssignmentView: typeof import('./src/components/admin/assign/AssignmentView.vue')['default']
    CourseDialog: typeof import('./src/components/admin/CourseDialog.vue')['default']
    CustomFooter: typeof import('./src/components/CustomFooter.vue')['default']
    CustomNavbar: typeof import('./src/components/navbar/CustomNavbar.vue')['default']
    EditOfferedCourse: typeof import('./src/components/admin/EditOfferedCourse.vue')['default']
    EnrollCheckbox: typeof import('./src/components/subject/EnrollCheckbox.vue')['default']
    EnrollmentForm: typeof import('./src/components/EnrollmentForm.vue')['default']
    EnrollmentOverview: typeof import('./src/components/EnrollmentOverview.vue')['default']
    EnrollmentPhase: typeof import('./src/components/admin/EnrollmentPhase.vue')['default']
    FilterDialog: typeof import('./src/components/FilterDialog.vue')['default']
    FilterSection: typeof import('./src/components/FilterSection.vue')['default']
    InfoDialog: typeof import('./src/components/InfoDialog.vue')['default']
    LocaleOptionsList: typeof import('./src/components/navbar/LocaleOptionsList.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    NavbarDesktop: typeof import('./src/components/navbar/NavbarDesktop.vue')['default']
    NavbarMobile: typeof import('./src/components/navbar/NavbarMobile.vue')['default']
    OfferedCourses: typeof import('./src/components/admin/OfferedCourses.vue')['default']
    OfferedCoursesTable: typeof import('./src/components/admin/phase/OfferedCoursesTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubjectDetails: typeof import('./src/components/subject/SubjectDetails.vue')['default']
    SubjectDialog: typeof import('./src/components/subject/SubjectDialog.vue')['default']
    SubjectTable: typeof import('./src/components/subject/SubjectTable.vue')['default']
    SubjectTableRow: typeof import('./src/components/subject/SubjectTableRow.vue')['default']
    SubjectTile: typeof import('./src/components/subject/SubjectTile.vue')['default']
    SubjectTiles: typeof import('./src/components/subject/SubjectTiles.vue')['default']
    ThemeOptionsList: typeof import('./src/components/navbar/ThemeOptionsList.vue')['default']
  }
}
