/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EnrollmentOverview: typeof import('./src/components/EnrollmentOverview.vue')['default']
    FilterSection: typeof import('./src/components/FilterSection.vue')['default']
    InfoDialog: typeof import('./src/components/InfoDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubjectDialog: typeof import('./src/components/SubjectDialog.vue')['default']
    SubjectTable: typeof import('./src/components/SubjectTable.vue')['default']
    SubjectTile: typeof import('./src/components/SubjectTile.vue')['default']
  }
}
