/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/phase-[phaseId]/': RouteRecordInfo<'/admin/phase-[phaseId]/', '/admin/phase-:phaseId', { phaseId: ParamValue<true> }, { phaseId: ParamValue<false> }>,
    '/admin/phase-[phaseId]/edit': RouteRecordInfo<'/admin/phase-[phaseId]/edit', '/admin/phase-:phaseId/edit', { phaseId: ParamValue<true> }, { phaseId: ParamValue<false> }>,
  }
}
