/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    'admin.index': RouteRecordInfo<'admin.index', '/admin', Record<never, never>, Record<never, never>>,
    'admin.courses.index': RouteRecordInfo<'admin.courses.index', '/admin/courses', Record<never, never>, Record<never, never>>,
    'admin.courses.upload': RouteRecordInfo<'admin.courses.upload', '/admin/courses/upload', Record<never, never>, Record<never, never>>,
    'admin.phases.index': RouteRecordInfo<'admin.phases.index', '/admin/phases', Record<never, never>, Record<never, never>>,
    'admin.phases.phaseId.index': RouteRecordInfo<'admin.phases.phaseId.index', '/admin/phases/:phaseId', { phaseId: ParamValue<true> }, { phaseId: ParamValue<false> }>,
    'admin.phases.phaseId.edit': RouteRecordInfo<'admin.phases.phaseId.edit', '/admin/phases/:phaseId/edit', { phaseId: ParamValue<true> }, { phaseId: ParamValue<false> }>,
    '/results': RouteRecordInfo<'/results', '/results', Record<never, never>, Record<never, never>>,
  }
}
